/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleCliente;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ConectaBanco;
import modelo.ModeloCliente;
import modelo.ModeloTabela;

/**
 *
 * @author Victor
 */
public class TelaCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCliente
     */
    
    public void setPosicao(){ //centraliza tela
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) /2, (d.height - this.getSize().height) /2);
    }
    
    ModeloCliente mod = new ModeloCliente();
    ControleCliente control = new ControleCliente();
    ConectaBanco conex = new ConectaBanco();
    int flag = 0;
    
    public TelaCliente() {
        initComponents();
        preencherTabela("select *from clientes order by nome_cliente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        complemento = new javax.swing.JTextField();
        cep = new javax.swing.JFormattedTextField();
        telefone = new javax.swing.JFormattedTextField();
        celular = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        novo = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        pesquisa = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelacliente = new javax.swing.JTable();
        nome = new javax.swing.JTextField();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cod:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Endereço:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Complemento:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Celular:");

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        id.setEnabled(false);

        endereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        endereco.setEnabled(false);

        complemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        complemento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        complemento.setEnabled(false);
        complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoActionPerformed(evt);
            }
        });

        try {
            cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cep.setEnabled(false);
        cep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        telefone.setEnabled(false);
        telefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celular.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        celular.setEnabled(false);
        celular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bairro:");

        bairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bairro.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        bairro.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cidade:");

        cidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        cidade.setEnabled(false);
        cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidadeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CEP:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Telefone:");

        novo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/disk.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.setEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        editar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_edit.png"))); // NOI18N
        editar.setText("Editar");
        editar.setEnabled(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        excluir.setText("Excluir");
        excluir.setEnabled(false);
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        pesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        sair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        sair.setText("Fechar");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        tabelacliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelacliente);

        nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nome.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(endereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bairro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo)
                    .addComponent(salvar)
                    .addComponent(cancelar)
                    .addComponent(pesquisar)
                    .addComponent(sair)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar)
                    .addComponent(excluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementoActionPerformed

    private void cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidadeActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        flag = 1;
        salvar.setEnabled(true);
        cancelar.setEnabled(true);
        nome.setEnabled(true);
        endereco.setEnabled(true);
        complemento.setEnabled(true);
        bairro.setEnabled(true);
        cidade.setEnabled(true);
        cep.setEnabled(true);
        telefone.setEnabled(true);
        celular.setEnabled(true);
        novo.setEnabled(false);
        pesquisa.setEnabled(false);
        pesquisar.setEnabled(false);
        editar.setEnabled(false);
        excluir.setEnabled(false);
        nome.setText("");
        endereco.setText("");
        complemento.setText("");
        cidade.setText("");
        bairro.setText("");
        cep.setText("");
        telefone.setText("");
        celular.setText("");
        id.setText("");
        pesquisa.setText("");
    }//GEN-LAST:event_novoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if (flag == 1){
            if(nome.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha nome para continuar");
                nome.requestFocus();
            }else if(endereco.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha endereço para continuar");
                endereco.requestFocus();
            }else if(cidade.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha cidade para continuar");
                cidade.requestFocus();
            }else if(bairro.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha bairro para continuar");
                bairro.requestFocus();
            }else{
                mod.setNome(nome.getText());      
                mod.setEndereco(endereco.getText());
                mod.setComplemento(complemento.getText());
                mod.setCidade(cidade.getText());
                mod.setBairro(bairro.getText());
                mod.setCep(cep.getText());
                mod.setTelefone(telefone.getText());
                mod.setCelular(celular.getText());
                control.Salvar(mod);
                nome.setText("");
                endereco.setText("");
                complemento.setText("");
                cidade.setText("");
                bairro.setText("");
                cep.setText("");
                telefone.setText("");
                celular.setText("");
                salvar.setEnabled(false);
                cancelar.setEnabled(false);
                nome.setEnabled(false);
                endereco.setEnabled(false);
                complemento.setEnabled(false);
                bairro.setEnabled(false);
                cidade.setEnabled(false);
                cep.setEnabled(false);
                telefone.setEnabled(false);
                celular.setEnabled(false);
                novo.setEnabled(true);
                pesquisa.setEnabled(true);
                pesquisar.setEnabled(true);
                preencherTabela("select *from clientes order by nome_cliente");
            }
        } else {
            if(nome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha nome para continuar");
            nome.requestFocus();
            }else if(endereco.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha endereço para continuar");
                endereco.requestFocus();
            }else if(cidade.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha cidade para continuar");
                cidade.requestFocus();
            }else if(bairro.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Preencha bairro para continuar");
                bairro.requestFocus();
            }else{   
                mod.setId((Integer.parseInt(id.getText()))); 
                mod.setNome(nome.getText());
                mod.setEndereco(endereco.getText());
                mod.setComplemento(complemento.getText());
                mod.setCidade(cidade.getText());
                mod.setBairro(bairro.getText());
                mod.setCep(cep.getText());
                mod.setTelefone(telefone.getText());
                mod.setCelular(celular.getText());
                control.Editar(mod);
                id.setText("");
                nome.setText("");
                endereco.setText("");
                complemento.setText("");
                cidade.setText("");
                bairro.setText("");
                cep.setText("");
                telefone.setText("");
                celular.setText("");
                endereco.setEnabled(false);
                complemento.setEnabled(false);
                cidade.setEnabled(false);
                bairro.setEnabled(false);
                cep.setEnabled(false);
                telefone.setEnabled(false);
                celular.setEnabled(false);
                nome.setEnabled(false);
                salvar.setEnabled(false);
                editar.setEnabled(false);
                excluir.setEnabled(false);
                pesquisa.setEnabled(true);
                cancelar.setEnabled(false);
                pesquisa.setEnabled(true);
                pesquisar.setEnabled(true);
                novo.setEnabled(true);
                preencherTabela("select *from clientes order by nome_cliente");
            }
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        this.dispose();
    }//GEN-LAST:event_sairActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
            nome.setText("");
            endereco.setText("");
            complemento.setText("");
            cidade.setText("");
            bairro.setText("");
            cep.setText("");
            telefone.setText("");
            celular.setText("");
            id.setText("");
            salvar.setEnabled(false);
            cancelar.setEnabled(false);
            nome.setEnabled(false);
            endereco.setEnabled(false);
            complemento.setEnabled(false);
            bairro.setEnabled(false);
            cidade.setEnabled(false);
            cep.setEnabled(false);
            telefone.setEnabled(false);
            celular.setEnabled(false);
            novo.setEnabled(true);
            pesquisa.setEnabled(true);
            pesquisar.setEnabled(true);
    }//GEN-LAST:event_cancelarActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        mod.setPesquisa(pesquisa.getText());
        ModeloCliente model = control.buscaCliente(mod);
        id.setText(String.valueOf(model.getId()));
        nome.setText(model.getNome());
        endereco.setText(model.getEndereco());
        complemento.setText(model.getComplemento());
        cidade.setText(model.getCidade());
        bairro.setText(model.getBairro());
        cep.setText(model.getCep());
        telefone.setText(model.getTelefone());
        celular.setText(model.getCelular());
        preencherTabela("select *from clientes where nome_cliente like'%"+mod.getPesquisa()+"%'");
        nome.setText("");
        endereco.setText("");
        complemento.setText("");
        cidade.setText("");
        bairro.setText("");
        cep.setText("");
        telefone.setText("");
        celular.setText("");
        id.setText("");
        pesquisa.setText("");
    }//GEN-LAST:event_pesquisarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        flag = 2;
        salvar.setEnabled(true);
        cancelar.setEnabled(true);
        nome.setEnabled(true);
        endereco.setEnabled(true);
        complemento.setEnabled(true);
        bairro.setEnabled(true);
        cidade.setEnabled(true);
        cep.setEnabled(true);
        telefone.setEnabled(true);
        celular.setEnabled(true);
        novo.setEnabled(false);
        pesquisa.setEnabled(false);
        pesquisar.setEnabled(false);
        editar.setEnabled(false);
        excluir.setEnabled(false);
        pesquisa.setText("");
    }//GEN-LAST:event_editarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir este cliente?", "Excluir", resposta);
        if(resposta == JOptionPane.YES_OPTION){
            mod.setId(Integer.parseInt(id.getText()));
            control.Excluir(mod);
            nome.setText("");
            endereco.setText("");
            complemento.setText("");
            cidade.setText("");
            bairro.setText("");
            cep.setText("");
            telefone.setText("");
            celular.setText("");
            id.setText("");
            pesquisa.setText("");
            salvar.setEnabled(false);
            cancelar.setEnabled(false);
            nome.setEnabled(false);
            endereco.setEnabled(false);
            complemento.setEnabled(false);
            bairro.setEnabled(false);
            cidade.setEnabled(false);
            cep.setEnabled(false);
            telefone.setEnabled(false);
            celular.setEnabled(false);
            novo.setEnabled(true);
            pesquisa.setEnabled(true);
            pesquisar.setEnabled(true);
            editar.setEnabled(false);
            excluir.setEnabled(false);
            preencherTabela("select *from clientes order by nome_cliente");
        }        
    }//GEN-LAST:event_excluirActionPerformed

    private void tabelaclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaclienteMouseClicked
        id.setText("");
        nome.setText("");
        endereco.setText("");
        complemento.setText("");
        cidade.setText("");
        bairro.setText("");
        cep.setText("");
        telefone.setText("");
        celular.setText("");
        novo.setEnabled(true);
        endereco.setEnabled(false);
        complemento.setEnabled(false);
        cidade.setEnabled(false);
        bairro.setEnabled(false);
        cep.setEnabled(false);
        telefone.setEnabled(false);
        celular.setEnabled(false);
        nome.setEnabled(false);
        salvar.setEnabled(false);
        editar.setEnabled(false);
        excluir.setEnabled(false);
        pesquisar.setEnabled(true);
        cancelar.setEnabled(false);
        pesquisa.setEnabled(true);
        String nome_cliente =""+tabelacliente.getValueAt(tabelacliente.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select *from clientes where nome_cliente='"+nome_cliente+"'");
        try {
            conex.rs.first();
            id.setText(String.valueOf(conex.rs.getInt("id_cliente")));
            nome.setText(conex.rs.getString("nome_cliente"));
            endereco.setText(conex.rs.getString("endereco_cliente"));
            complemento.setText(conex.rs.getString("complemento_cliente"));
            cidade.setText(conex.rs.getString("cidade_cliente"));
            bairro.setText(conex.rs.getString("bairro_cliente"));
            cep.setText(conex.rs.getString("cep_cliente"));
            telefone.setText(conex.rs.getString("telefone_cliente"));
            celular.setText(conex.rs.getString("celular_cliente"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar cliente"+ex);
        }
        conex.desconecta();
        editar.setEnabled(true);
        excluir.setEnabled(true);
    }//GEN-LAST:event_tabelaclienteMouseClicked

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Nome", "Endereço", "Telefone", "Celular"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("id_cliente"),conex.rs.getString("nome_cliente"),conex.rs.getString("endereco_cliente"),conex.rs.getString("telefone_cliente"),conex.rs.getString("celular_cliente")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Busque por outro cliente para preencher tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelacliente.setModel(modelo);
        tabelacliente.getColumnModel().getColumn(0).setPreferredWidth(59);
        tabelacliente.getColumnModel().getColumn(0).setResizable(false);
        tabelacliente.getColumnModel().getColumn(1).setPreferredWidth(325);
        tabelacliente.getColumnModel().getColumn(1).setResizable(false);
        tabelacliente.getColumnModel().getColumn(2).setPreferredWidth(275);
        tabelacliente.getColumnModel().getColumn(2).setResizable(false);
        tabelacliente.getColumnModel().getColumn(3).setPreferredWidth(120);
        tabelacliente.getColumnModel().getColumn(3).setResizable(false);
        tabelacliente.getColumnModel().getColumn(4).setPreferredWidth(130);
        tabelacliente.getColumnModel().getColumn(4).setResizable(false);
        tabelacliente.getTableHeader().setReorderingAllowed(false);
        tabelacliente.setAutoResizeMode(tabelacliente.AUTO_RESIZE_OFF);
        tabelacliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField complemento;
    private javax.swing.JButton editar;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JButton novo;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton sair;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tabelacliente;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
