/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Dimension;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ConectaBanco;
import modelo.ModeloTabela;

/**
 *
 * @author Victor
 */
public class TelaRelatorioVendaNome extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorioVendaNome
     */
    
    public void setPosicao(){ //centraliza tela
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) /2, (d.height - this.getSize().height) /2);
    }
    
    ConectaBanco conex = new ConectaBanco();
    int cod = 0;
    
    public TelaRelatorioVendaNome() {
        initComponents();
        teste.setText("Detalhes Da Compra ID: ");
        limpatabela("select *from venda inner join itens_venda_produto "
                + "on venda.id_venda = itens_venda_produto.id_venda inner join produtos "
                + "on itens_venda_produto.id_produto = produtos.id_produto where venda.id_venda = '"+0+"'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botaopesquisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        nomecliente = new javax.swing.JTextField();
        teste = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaprodutos = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatorio de Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome Cliente:");

        botaopesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaopesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        botaopesquisa.setText("Pesquisar");
        botaopesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Compras");

        tabela.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nomecliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeclienteActionPerformed(evt);
            }
        });

        teste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teste.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        tabelaprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabelaprodutos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaopesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teste, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaopesquisa)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teste, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaopesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopesquisaActionPerformed
        teste.setText("Detalhes Da Compra ID: ");
        limpatabela("select *from venda inner join itens_venda_produto "
                + "on venda.id_venda = itens_venda_produto.id_venda inner join produtos "
                + "on itens_venda_produto.id_produto = produtos.id_produto where venda.id_venda = '"+0+"'");
        preencherTabela("select *from venda inner join clientes on venda.id_cliente = clientes.id_cliente where nome_cliente like '%"+nomecliente.getText()+"%' order by data");
    }//GEN-LAST:event_botaopesquisaActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int cod = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);
        preencherTabelaDetalhes("select *from venda inner join itens_venda_produto "
                + "on venda.id_venda = itens_venda_produto.id_venda inner join produtos "
                + "on itens_venda_produto.id_produto = produtos.id_produto where venda.id_venda = '"+cod+"'");
        teste.setText("Detalhes Da Compra ID: " +String.valueOf(cod));
    }//GEN-LAST:event_tabelaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomeclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeclienteActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"ID", "Data Venda", "Valor da Venda", "Cliente"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                Date data1 = conex.rs.getDate("data");
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                String dataFormatada = formato.format(data1);
                dados.add(new Object[]{conex.rs.getInt("id_venda"),dataFormatada,conex.rs.getFloat("valor_venda"),conex.rs.getString("nome_cliente")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Busque por outro cliente para preencher tabela.\nNenhuma compra feita pelo cliente pesquisado.");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabela.setModel(modelo);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(59);
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(120);
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(353);
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    public void limpatabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Produtos", "Quantidade", "Valor Unit", "Valor Total"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                float valorProduto = conex.rs.getFloat("preco_produto");
                int qunatidadeVendida = conex.rs.getInt("quantidade");
                DecimalFormat df = new DecimalFormat("##,##");
                dados.add(new Object[]{conex.rs.getString("nome_produto"),conex.rs.getString("quantidade"), conex.rs.getString("preco_produto"), df.format(valorProduto*qunatidadeVendida)});
            }while(conex.rs.next());
        }catch(SQLException ex){
           
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaprodutos.setModel(modelo);
        tabelaprodutos.getColumnModel().getColumn(0).setPreferredWidth(331);
        tabelaprodutos.getColumnModel().getColumn(0).setResizable(false);        
        tabelaprodutos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(1).setResizable(false);
        tabelaprodutos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(2).setResizable(false);        
        tabelaprodutos.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(3).setResizable(false);
        tabelaprodutos.getTableHeader().setReorderingAllowed(false);
        tabelaprodutos.setAutoResizeMode(tabelaprodutos.AUTO_RESIZE_OFF);
        tabelaprodutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
    
    public void preencherTabelaDetalhes(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Produtos", "Quantidade", "Valor Unit", "Valor Total"};
        conex.conexao();
        conex.executaSql(Sql);
        try{
            conex.rs.first();
            do{
                float valorProduto = conex.rs.getFloat("preco_produto");
                int qunatidadeVendida = conex.rs.getInt("quantidade");
                DecimalFormat df = new DecimalFormat("##.##");
                dados.add(new Object[]{conex.rs.getString("nome_produto"),conex.rs.getString("quantidade"), conex.rs.getString("preco_produto"), df.format(valorProduto*qunatidadeVendida)});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Busque por outro cliente para preencher tabela"+ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaprodutos.setModel(modelo);
        tabelaprodutos.getColumnModel().getColumn(0).setPreferredWidth(331);
        tabelaprodutos.getColumnModel().getColumn(0).setResizable(false);        
        tabelaprodutos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(1).setResizable(false);
        tabelaprodutos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(2).setResizable(false);        
        tabelaprodutos.getColumnModel().getColumn(3).setPreferredWidth(100);
        tabelaprodutos.getColumnModel().getColumn(3).setResizable(false);
        tabelaprodutos.getTableHeader().setReorderingAllowed(false);
        tabelaprodutos.setAutoResizeMode(tabelaprodutos.AUTO_RESIZE_OFF);
        tabelaprodutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaopesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomecliente;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaprodutos;
    private javax.swing.JLabel teste;
    // End of variables declaration//GEN-END:variables
}
