/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleVenda;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ConectaBanco;
import modelo.ModeloTabela;
import modelo.ModeloVenda;

/**
 *
 * @author Victor
 */
public class TelaVenda extends javax.swing.JInternalFrame {

    ConectaBanco conex = new ConectaBanco();
    ModeloVenda mod = new ModeloVenda();
    ControleVenda control = new ControleVenda();
    int flag = 1, codVenda;
    float preco_produto, total = 0;

    /**
     * Creates new form TelaVenda
     */
    public void setPosicao() { //centraliza tela
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public TelaVenda() {
        initComponents();

        conex.conexao();
        try {
            PreparedStatement pst = conex.con.prepareStatement("insert into venda (valor_venda) values(?)");
            pst.setFloat(1, 0);
            pst.execute();
            conex.executaSql("select *from venda");
            conex.rs.last();
            codVenda = conex.rs.getInt("id_venda");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "ERRO: " + ex);
        }

        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date hoje = new Date();
        data.setText(df.format(hoje));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buscacliente = new javax.swing.JButton();
        nomecliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        data = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        nomeproduto = new javax.swing.JTextField();
        buscaproduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelapesquisa = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaitemvenda = new javax.swing.JTable();
        valortotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        buscacliente1 = new javax.swing.JButton();
        nomecliente1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        quantidade1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        valor1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        data1 = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();
        nomeproduto1 = new javax.swing.JTextField();
        buscaproduto1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelapesquisa1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaitemvenda1 = new javax.swing.JTable();
        valortotal1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        finalizar1 = new javax.swing.JButton();
        cancelar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Cliente:");

        buscacliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscacliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscacliente.setText("Buscar");
        buscacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaclienteActionPerformed(evt);
            }
        });

        nomecliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Produto:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Quantidade:");

        quantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidadeFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Valor Unitario:");

        valor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        valor.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data:");

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        data.setEnabled(false);
        data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_add.png"))); // NOI18N
        jButton4.setText("Adicionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        nomeproduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buscaproduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscaproduto.setText("Buscar");
        buscaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaprodutoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tabela de Pesquisa:");

        tabelapesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelapesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelapesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelapesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelapesquisa);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Itens da Venda:");

        tabelaitemvenda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaitemvenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaitemvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaitemvendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaitemvenda);

        valortotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valortotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valortotal.setText("0.0");
        valortotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        valortotal.setEnabled(false);
        valortotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortotalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Valor Total:");

        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelar.setText("Cancelar Venda");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        finalizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        finalizar.setText("Finalizar Venda");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cart_delete.png"))); // NOI18N
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addGap(330, 330, 330)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscaproduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(nomecliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buscacliente))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(data, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(115, 115, 115)
                                .addComponent(finalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valortotal)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscacliente)
                    .addComponent(nomecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaproduto)
                    .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cancelar)
                    .addComponent(finalizar)
                    .addComponent(jButton3)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame1.setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nome do Cliente:");

        buscacliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscacliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscacliente1.setText("Buscar");
        buscacliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscacliente1ActionPerformed(evt);
            }
        });

        nomecliente1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Produto:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Quantidade:");

        quantidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidade1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantidade1FocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Valor Unitario:");

        valor1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valor1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        valor1.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Data:");

        try {
            data1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        data1.setEnabled(false);
        data1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jButton5.setText("Adicionar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        nomeproduto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buscaproduto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscaproduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscaproduto1.setText("Buscar");
        buscaproduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaproduto1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tabela de Pesquisa:");

        tabelapesquisa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelapesquisa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelapesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelapesquisa1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelapesquisa1);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Itens da Venda:");

        tabelaitemvenda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelaitemvenda1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabelaitemvenda1);

        valortotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        valortotal1.setEnabled(false);
        valortotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortotal1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Valor Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel11)
                                    .addGap(330, 330, 330)
                                    .addComponent(jLabel12))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(nomeproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(buscaproduto1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(nomecliente1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(buscacliente1))
                                        .addComponent(jLabel10))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(data1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valortotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscacliente1)
                    .addComponent(nomecliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaproduto1)
                    .addComponent(quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valortotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        finalizar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        finalizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        finalizar1.setText("Finalizar Venda");
        finalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizar1ActionPerformed(evt);
            }
        });

        cancelar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelar1.setText("Cancelar Venda");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finalizar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelar1)
                        .addGap(232, 232, 232))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizar1)
                    .addComponent(cancelar1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (nomeproduto.getText().isEmpty()) {
            nomeproduto.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Busque pelo produto");
        } else {
            try {
                int idVenda, quantidadee = 0;
                conex.conexao();
                conex.executaSql("select *from produtos where nome_produto = '" + nomeproduto.getText() + "'");
                conex.rs.first();
                quantidadee = conex.rs.getInt("quantidade_produto");
                if (quantidadee >= Integer.parseInt(quantidade.getText())) {
                    mod.setNomeProduto(nomeproduto.getText());
                    mod.setQuantidadeItem(Integer.parseInt(quantidade.getText()));
                    mod.setIdVenda(codVenda);
                    control.adicionaItem(mod);
                    preencherItensVenda("select *from produtos inner join itens_venda_produto "
                            + "on produtos.id_produto = itens_venda_produto.id_produto inner join venda "
                            + "on venda.id_venda = itens_venda_produto.id_venda where venda.id_venda = " + codVenda);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "A quantidade desejada não está disponivel no estoque!");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Eroo ao pesquisar quantidade\nEroo: " + ex);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(rootPane, "Quantidade Invalida", "Erro", 1);
            }
            nomeproduto.setText("");
            quantidade.setText("");
            valor.setText("");
            preencherTabelaProduto("select *from produtos where nome_produto like'%" + nomeproduto.getText() + "%'");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buscaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaclienteActionPerformed
        flag = 1;
        preencherTabelaCliente("select *from clientes where nome_cliente like '%" + nomecliente.getText() + "%'");
    }//GEN-LAST:event_buscaclienteActionPerformed

    private void buscaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaprodutoActionPerformed
        if (nomecliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para continuar");
            nomecliente.requestFocus();
        } else {
            flag = 2;
            preencherTabelaProduto("select *from produtos where nome_produto like'%" + nomeproduto.getText() + "%'");
        }
    }//GEN-LAST:event_buscaprodutoActionPerformed

    private void tabelapesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelapesquisaMouseClicked
        if (flag == 1) {
            String nome_cliente = "" + tabelapesquisa.getValueAt(tabelapesquisa.getSelectedRow(), 1);
            nomecliente.setText(nome_cliente);
        } else {
            conex.conexao();
            try {
                String nome_produto = "" + tabelapesquisa.getValueAt(tabelapesquisa.getSelectedRow(), 1);
                String id_produto = "" + tabelapesquisa.getValueAt(tabelapesquisa.getSelectedRow(), 0);
                conex.executaSql("select *from produtos where id_produto='" + id_produto + "'");
                conex.rs.first();
                preco_produto = conex.rs.getFloat("preco_produto");
                valor.setText(String.valueOf(preco_produto));
                nomeproduto.setText(nome_produto);
                quantidade.setText("1");
                conex.desconecta();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao pesquisar o preço");
            }
        }
    }//GEN-LAST:event_tabelapesquisaMouseClicked

    private void quantidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidadeFocusGained

    }//GEN-LAST:event_quantidadeFocusGained

    private void valortotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortotalActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        mod.setIdVenda(codVenda);
        mod.setNomeCliente(nomecliente.getText());
        mod.setValorVenda(Float.parseFloat(valortotal.getText()));
        control.FechaVenda(mod);
        dispose();
    }//GEN-LAST:event_finalizarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        control.CancelaVenda();
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void buscacliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscacliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscacliente1ActionPerformed

    private void quantidade1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantidade1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidade1FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void buscaproduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaproduto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaproduto1ActionPerformed

    private void tabelapesquisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelapesquisa1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelapesquisa1MouseClicked

    private void valortotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortotal1ActionPerformed

    private void finalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalizar1ActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nome_produto = "" + tabelaitemvenda.getValueAt(tabelaitemvenda.getSelectedRow(), 0);
        mod.setNomeProduto(nome_produto);
        control.removeItem(mod);
        nomeproduto.setText("");
        quantidade.setText("");
        valor.setText("");
        preencherItensVenda("select *from produtos inner join itens_venda_produto "
                + "on produtos.id_produto = itens_venda_produto.id_produto inner join venda "
                + "on venda.id_venda = itens_venda_produto.id_venda where venda.id_venda = " + codVenda);
        preencherTabelaProduto("select *from produtos where nome_produto like'%" + nomeproduto.getText() + "%'");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelaitemvendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaitemvendaMouseClicked

    }//GEN-LAST:event_tabelaitemvendaMouseClicked

    public void preencherTabelaCliente(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome"};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("id_cliente"), conex.rs.getString("nome_cliente")});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque por outro cliente para preencher tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelapesquisa.setModel(modelo);
        tabelapesquisa.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelapesquisa.getColumnModel().getColumn(0).setResizable(false);
        tabelapesquisa.getColumnModel().getColumn(1).setPreferredWidth(625);
        tabelapesquisa.getColumnModel().getColumn(1).setResizable(false);
        tabelapesquisa.getTableHeader().setReorderingAllowed(false);
        tabelapesquisa.setAutoResizeMode(tabelapesquisa.AUTO_RESIZE_OFF);
        tabelapesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    public void preencherTabelaProduto(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Produto", "Valor", "Quantidade Disp."};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                int quant = conex.rs.getInt("quantidade_produto");
                if (quant == 0) {

                } else {
                    dados.add(new Object[]{conex.rs.getInt("id_produto"), conex.rs.getString("nome_produto"), conex.rs.getFloat("preco_produto"), quant});
                }
            } while (conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque por outro produto para preencher tabela" + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelapesquisa.setModel(modelo);
        tabelapesquisa.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelapesquisa.getColumnModel().getColumn(0).setResizable(false);
        tabelapesquisa.getColumnModel().getColumn(1).setPreferredWidth(415);
        tabelapesquisa.getColumnModel().getColumn(1).setResizable(false);
        tabelapesquisa.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabelapesquisa.getColumnModel().getColumn(2).setResizable(false);
        tabelapesquisa.getColumnModel().getColumn(3).setPreferredWidth(110);
        tabelapesquisa.getColumnModel().getColumn(3).setResizable(false);
        tabelapesquisa.getTableHeader().setReorderingAllowed(false);
        tabelapesquisa.setAutoResizeMode(tabelapesquisa.AUTO_RESIZE_OFF);
        tabelapesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conex.desconecta();
    }

    public void preencherItensVenda(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Descrição", "Quantidade", "Valor Total"};
        conex.conexao();
        conex.executaSql(Sql);
        try {
            conex.rs.first();
            do {
                float valorProduto = conex.rs.getFloat("preco_produto");
                int qunatidadeVendida = conex.rs.getInt("quantidade");
                dados.add(new Object[]{conex.rs.getString("nome_produto"), conex.rs.getString("quantidade"), valorProduto * qunatidadeVendida});
            } while (conex.rs.next());
        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar produto.\nErro: " + ex);
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaitemvenda.setModel(modelo);
        tabelaitemvenda.getColumnModel().getColumn(0).setPreferredWidth(500);
        tabelaitemvenda.getColumnModel().getColumn(0).setResizable(false);
        tabelaitemvenda.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabelaitemvenda.getColumnModel().getColumn(1).setResizable(false);
        tabelaitemvenda.getColumnModel().getColumn(2).setPreferredWidth(125);
        tabelaitemvenda.getColumnModel().getColumn(2).setResizable(false);
        tabelaitemvenda.getTableHeader().setReorderingAllowed(false);
        tabelaitemvenda.setAutoResizeMode(tabelaitemvenda.AUTO_RESIZE_OFF);
        tabelaitemvenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        SomaProduto();
    }

    public void SomaProduto() {
        total = 0;
        int qtd = 0;
        float valor = 0;
        conex.executaSql("select *from itens_venda_produto inner join produtos "
                + "on itens_venda_produto.id_produto = produtos.id_produto where id_venda = " + codVenda);
        try {
            while (conex.rs.next()) {
                qtd = conex.rs.getInt("quantidade");
                valor = conex.rs.getFloat("preco_produto");
                total = total + conex.rs.getFloat("preco_produto") * conex.rs.getInt("quantidade");
            }
            valortotal.setText(String.valueOf(total));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Eroo na soma do total\nErro: " + ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscacliente;
    private javax.swing.JButton buscacliente1;
    private javax.swing.JButton buscaproduto;
    private javax.swing.JButton buscaproduto1;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JFormattedTextField data1;
    private javax.swing.JButton finalizar;
    private javax.swing.JButton finalizar1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nomecliente;
    private javax.swing.JTextField nomecliente1;
    private javax.swing.JTextField nomeproduto;
    private javax.swing.JTextField nomeproduto1;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField quantidade1;
    private javax.swing.JTable tabelaitemvenda;
    private javax.swing.JTable tabelaitemvenda1;
    private javax.swing.JTable tabelapesquisa;
    private javax.swing.JTable tabelapesquisa1;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valortotal;
    private javax.swing.JTextField valortotal1;
    // End of variables declaration//GEN-END:variables
}
